name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'  # Use a more recent LTS version of Node.js

      - name: Install Packages and Build Application
        run: |
          npm install -g @vue/cli
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3  # Consider using this action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  # Adjust if you deploy to a different branch